# Generated by Django 4.2.10 on 2024-02-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=20)),
                ('email', models.EmailField(default='', max_length=20)),
                ('contact', models.FloatField()),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=300)),
                ('comment', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
